/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.music;

import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author necia
 */
public class MusicGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicGUI
     */
    
    DefaultListModel generalModel, likedModel, popModel, rockModel;
    GeneralPlaylist generalPlaylist;
    LikedPlaylist likedPlaylist;
    PopPlaylist popPlaylist;
    RockPlaylist rockPlaylist;
    int pressedSongIndex;
    
    public MusicGUI() {
        initComponents();
        generalModel = new DefaultListModel();
        likedModel = new DefaultListModel();
        popModel = new DefaultListModel();
        rockModel = new DefaultListModel();

        generalPlaylist = new GeneralPlaylist();
        likedPlaylist = new LikedPlaylist();
        popPlaylist = new PopPlaylist();
        rockPlaylist = new RockPlaylist();
        
        Song song1 = new Song("I like you", "BamBam", "Pop", false);
        Song song2 = new Song("Mama", "Brothers", "Rock", false);
        Song song3 = new Song("Lorem Ipsum", "Nerds", "Pop", false);
        Song song4 = new Song("Ipsumpsum", "Nerds", "Pop", true);
        Song song5 = new Song("XOXO", "BamBam", "Rock", false);
        Song song6 = new Song("BOBO", "Nerds", "Pop", false);
        
        generalPlaylist.addSong(song1);
        generalPlaylist.addSong(song2);
        generalPlaylist.addSong(song3);
        
        likedPlaylist.addSong(song4);
        
        popPlaylist.addSong(song5);
        
        rockPlaylist.addSong(song6);
        
        for (Song song: generalPlaylist.getSongs()) {
            generalModel.addElement(song);
        }
        generalDisplay.setModel(generalModel);
        
        for (Song song: likedPlaylist.getSongs()) {
            likedModel.addElement(song);
        }
        likedDisplay.setModel(likedModel);
        
        for (Song song: popPlaylist.getSongs()) {
            popModel.addElement(song);
        }
        popDisplay.setModel(popModel);
        
        for (Song song: rockPlaylist.getSongs()) {
            rockModel.addElement(song);
        }
        rockDisplay.setModel(rockModel);
        
        generalDisplay.getSelectionModel().addListSelectionListener(x -> {
            pressedSongIndex = generalDisplay.getSelectedIndex();
            System.out.println(pressedSongIndex);
        });
        
        likedDisplay.getSelectionModel().addListSelectionListener(x -> {
            pressedSongIndex = likedDisplay.getSelectedIndex();
            System.out.println(pressedSongIndex);
        });
        
        popDisplay.getSelectionModel().addListSelectionListener(x -> {
            pressedSongIndex = popDisplay.getSelectedIndex();
            System.out.println(pressedSongIndex);
        });
        
        rockDisplay.getSelectionModel().addListSelectionListener(x -> {
            pressedSongIndex = rockDisplay.getSelectedIndex();
            System.out.println(pressedSongIndex);
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        likedDisplay = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        generalDisplay = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        popDisplay = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        rockDisplay = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        titleText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        radioPop = new javax.swing.JRadioButton();
        radioRock = new javax.swing.JRadioButton();
        moveLiked = new javax.swing.JButton();
        movePop = new javax.swing.JButton();
        moveRock = new javax.swing.JButton();
        deleteSong = new javax.swing.JButton();
        searchSong = new javax.swing.JButton();
        playlistSize = new javax.swing.JButton();
        playlistRepeat = new javax.swing.JButton();
        addSong = new javax.swing.JButton();

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Music Manager");

        jLabel2.setText("Manage your music using this App!");

        likedDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(likedDisplay);

        generalDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(generalDisplay);

        popDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(popDisplay);

        rockDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(rockDisplay);

        jLabel3.setText("Your All Songs:");

        jLabel4.setText("Your Liked Songs:");

        jLabel5.setText("Your Pop Songs:");

        jLabel6.setText("Your Rock Songs:");

        jLabel7.setText("Title:");

        jLabel8.setText("Author:");

        jLabel9.setText("Genre:");

        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });

        radioPop.setText("Pop");

        radioRock.setText("Rock");

        moveLiked.setText("Move to: Liked Songs");
        moveLiked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLikedActionPerformed(evt);
            }
        });

        movePop.setText("Move to: Pop Songs");
        movePop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movePopActionPerformed(evt);
            }
        });

        moveRock.setText("Move to: Rock Songs");
        moveRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRockActionPerformed(evt);
            }
        });

        deleteSong.setText("Delete Song");
        deleteSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSongActionPerformed(evt);
            }
        });

        searchSong.setText("Search Song");
        searchSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSongActionPerformed(evt);
            }
        });

        playlistSize.setText("Playlist Size");
        playlistSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistSizeActionPerformed(evt);
            }
        });

        playlistRepeat.setText("Playlist Repeat");
        playlistRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistRepeatActionPerformed(evt);
            }
        });

        addSong.setText("Add Song");
        addSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(searchSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(playlistSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(playlistRepeat, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioRock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioPop, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(addSong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(moveLiked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movePop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moveRock, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moveLiked)
                            .addComponent(movePop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveRock)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(radioPop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteSong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchSong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playlistSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playlistRepeat)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextActionPerformed

    private void moveLikedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLikedActionPerformed
        // TODO add your handling code here:
        if(generalPlaylist.size() > 0) {
            Song song = generalPlaylist.getSong(pressedSongIndex);
            generalPlaylist.deleteSong(pressedSongIndex);
            generalModel.remove(pressedSongIndex);
            System.out.println(song);
            likedPlaylist.addSong(song);
            likedModel.addElement(song);
            song.setLiked(true);
            generalDisplay.setModel(generalModel);
            likedDisplay.setModel(likedModel);
        } else if (generalPlaylist.size() == 0) {
            JOptionPane.showMessageDialog(null, "No songs left in the playlist!");
        }
    }//GEN-LAST:event_moveLikedActionPerformed

    private void movePopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movePopActionPerformed
        // TODO add your handling code here:
        if(likedPlaylist.size() > 0) {
            Song song = likedPlaylist.getSong(pressedSongIndex);
            likedPlaylist.deleteSong(pressedSongIndex);
            likedModel.remove(pressedSongIndex);
            System.out.println(song);
            popPlaylist.addSong(song);
            popModel.addElement(song);
            song.setLiked(true);
            likedDisplay.setModel(likedModel);
            popDisplay.setModel(popModel);
        } else if (likedPlaylist.size() == 0) {
            JOptionPane.showMessageDialog(null, "No songs left in the playlist!");
        }
    }//GEN-LAST:event_movePopActionPerformed

    private void moveRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRockActionPerformed
        // TODO add your handling code here:
        if(likedPlaylist.size() > 0) {
            Song song = likedPlaylist.getSong(pressedSongIndex);
            likedPlaylist.deleteSong(pressedSongIndex);
            likedModel.remove(pressedSongIndex);
            System.out.println(song);
            rockPlaylist.addSong(song);
            rockModel.addElement(song);
            song.setLiked(true);
            likedDisplay.setModel(likedModel);
            rockDisplay.setModel(rockModel);
        } else if (likedPlaylist.size() == 0) {
            JOptionPane.showMessageDialog(null, "No songs left in the playlist!");
        }
    }//GEN-LAST:event_moveRockActionPerformed

    private void deleteSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSongActionPerformed
        // TODO add your handling code here:
//            likedPlaylist.deleteSong(pressedSongIndex);
//            likedModel.remove(pressedSongIndex);
//            likedDisplay.setModel(likedModel);
            
            boolean selectionLiked = likedDisplay.isSelectionEmpty();
            boolean selectionGeneral = generalDisplay.isSelectionEmpty();
            boolean selectionPop = popDisplay.isSelectionEmpty();
            boolean selectionRock = rockDisplay.isSelectionEmpty();
            
            if(selectionLiked == false) {
                likedPlaylist.deleteSong(pressedSongIndex);
                likedModel.remove(pressedSongIndex);
                likedDisplay.setModel(likedModel);
            } else if(selectionGeneral == false) {
                generalPlaylist.deleteSong(pressedSongIndex);
                generalModel.remove(pressedSongIndex);
                generalDisplay.setModel(generalModel);
            } else if(selectionPop == false) {
                popPlaylist.deleteSong(pressedSongIndex);
                popModel.remove(pressedSongIndex);
                popDisplay.setModel(popModel);
            } else if(selectionRock == false) {
                rockPlaylist.deleteSong(pressedSongIndex);
                rockModel.remove(pressedSongIndex);
                rockDisplay.setModel(rockModel);
            }
    }//GEN-LAST:event_deleteSongActionPerformed

    private void searchSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSongActionPerformed
        // TODO add your handling code here:
        String answer = JOptionPane.showInputDialog(null, "Type in title of the song you are looking for:");
//        if(generalPlaylist.searchSong(answer) == false) {
//            JOptionPane.showMessageDialog(null, "Not found!");
//        } else if(likedPlaylist.searchSong(answer) == false) {
//            JOptionPane.showMessageDialog(null, "Not found!");
//        } else if(popPlaylist.searchSong(answer) == false) {
//            JOptionPane.showMessageDialog(null, "Not found!");
//        } else if(rockPlaylist.searchSong(answer) == false) {
//            JOptionPane.showMessageDialog(null, "Not found!");
//        }
        
        if(generalPlaylist.searchSong(answer) == false || 
           likedPlaylist.searchSong(answer) == false || 
           popPlaylist.searchSong(answer) == false || 
           rockPlaylist.searchSong(answer) == false) 
        {
            JOptionPane.showMessageDialog(null, "Not found!");
        } else if ()
//        generalPlaylist.searchSong(answer);
        
    }//GEN-LAST:event_searchSongActionPerformed

    private void playlistSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistSizeActionPerformed
        // TODO add your handling code here:
        String answer = JOptionPane.showInputDialog(null, "Which playlist do you want to choose?\n1. General\n2. Liked\n3. Pop\n4. Rock");
        switch(answer) {
            case "1":
                JOptionPane.showMessageDialog(null, "Size of General Playlist is: " + generalPlaylist.size());
                break;
            case "2":
                JOptionPane.showMessageDialog(null, "Size of Liked Playlist is: " + likedPlaylist.size());
                break;
            case "3":
                JOptionPane.showMessageDialog(null, "Size of Pop Playlist is: " + popPlaylist.size());
                break;
            case "4":
                JOptionPane.showMessageDialog(null, "Size of Rock Playlist is: " + rockPlaylist.size());
                break;
        }
    }//GEN-LAST:event_playlistSizeActionPerformed

    private void playlistRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistRepeatActionPerformed
        // TODO add your handling code here:
        String answer = JOptionPane.showInputDialog(null, "Which playlist do you want to set on repeat?\n1. General\n2. Liked\n3. Pop\n4. Rock");
        switch(answer) {
            case "1":
                JOptionPane.showMessageDialog(null, "General Playlist is now set on repeat!");
                break;
            case "2":
                JOptionPane.showMessageDialog(null, "Liked Playlist is now set on repeat!");
                break;
            case "3":
                JOptionPane.showMessageDialog(null, "Pop Playlist is now set on repeat!");
                break;
            case "4":
                JOptionPane.showMessageDialog(null, "Rock Playlist is now set on repeat!");
                break;
        }
    }//GEN-LAST:event_playlistRepeatActionPerformed

    private void addSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongActionPerformed
        // TODO add your handling code here:
        String title = titleText.getText();
        String author = authorText.getText();
        String genre = null;
        if(radioPop.isSelected()) {
            genre = "Pop";
        } else if (radioRock.isSelected()){
            genre = "Rock";
        }
        Song song = new Song(title, author, genre, false);
        generalPlaylist.addSong(song);
        System.out.println(generalPlaylist.getSongs());
        generalModel.addElement(song);
    }//GEN-LAST:event_addSongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSong;
    private javax.swing.JTextField authorText;
    private javax.swing.JButton deleteSong;
    private javax.swing.JList<String> generalDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> likedDisplay;
    private javax.swing.JButton moveLiked;
    private javax.swing.JButton movePop;
    private javax.swing.JButton moveRock;
    private javax.swing.JButton playlistRepeat;
    private javax.swing.JButton playlistSize;
    private javax.swing.JList<String> popDisplay;
    private javax.swing.JRadioButton radioPop;
    private javax.swing.JRadioButton radioRock;
    private javax.swing.JList<String> rockDisplay;
    private javax.swing.JButton searchSong;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables
}
